'use client';

import { FileSpreadsheet } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useDashboard } from '../_context';

export function GoogleSheetsField() {
  const {
    autoExportEnabled,
    setAutoExportEnabled,
    exportSheetName,
    exportInvestmentAmount,
    setExportInvestmentAmount,
    exportTitle,
    setExportTitle,
  } = useDashboard();

  const handleToggle = () => {
    setAutoExportEnabled(!autoExportEnabled);
  };

  return (
    <Card className="border border-gray-200 bg-gray-50 p-4">
      <div className="flex items-center gap-3">
        <input
          type="checkbox"
          id="auto-export"
          checked={autoExportEnabled}
          onChange={handleToggle}
          className="h-4 w-4 rounded border-gray-300"
        />
        <Label htmlFor="auto-export" className="flex cursor-pointer items-center gap-2 font-medium">
          <FileSpreadsheet className="size-4" />
          Auto-export to Google Sheets
        </Label>
      </div>

      {autoExportEnabled && (
        <div className="mt-4 space-y-3 border-t border-gray-200 pt-4">
          <div>
            <Label className="text-xs font-semibold uppercase text-gray-600">
              Tab Name (Auto-generated by date)
            </Label>
            <p className="mt-1 rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-700">
              {exportSheetName}
            </p>
            <p className="mt-1 text-xs text-gray-500">
              Data will be exported to a day-wise tab in your master Google Sheet
            </p>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label htmlFor="investment-amount" className="text-xs font-semibold uppercase text-gray-600">
                Investment Amount (Optional)
              </Label>
              <Input
                id="investment-amount"
                type="text"
                placeholder="e.g., 10000"
                value={exportInvestmentAmount}
                onChange={(e) => setExportInvestmentAmount(e.target.value)}
                className="mt-1 text-sm"
              />
            </div>

            <div>
              <Label htmlFor="export-title" className="text-xs font-semibold uppercase text-gray-600">
                Title (Optional)
              </Label>
              <Input
                id="export-title"
                type="text"
                placeholder="e.g., Portfolio Analysis"
                value={exportTitle}
                onChange={(e) => setExportTitle(e.target.value)}
                className="mt-1 text-sm"
              />
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}
