'use client';

import { FileSpreadsheet } from 'lucide-react';
import Link from 'next/link';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import { useDashboard } from '../_context';

export function GoogleSheetsField({
  showInvestmentAmount = true,
}: {
  showInvestmentAmount?: boolean;
} = {}) {
  const {
    autoExportEnabled,
    setAutoExportEnabled,
    exportSpreadsheetUrl,
    exportSheetName,
    exportInvestmentAmount,
    setExportInvestmentAmount,
    exportTitle,
    setExportTitle,
    googleSheetsConnected,
  } = useDashboard();

  const handleToggle = () => {
    setAutoExportEnabled(!autoExportEnabled);
  };

  return (
    <Card className="border border-gray-200 bg-gray-50 p-4">
      <div className="flex items-center gap-3">
        <input
          type="checkbox"
          id="auto-export"
          checked={autoExportEnabled}
          onChange={handleToggle}
          className="h-4 w-4 rounded border-gray-300"
        />
        <Label htmlFor="auto-export" className="flex cursor-pointer items-center gap-2 font-medium">
          <FileSpreadsheet className="size-4" />
          Auto-export to Google Sheets
        </Label>
      </div>
      <div className="mt-2 flex items-center gap-2 text-xs">
        <span className={googleSheetsConnected ? 'text-emerald-600' : 'text-amber-700'}>
          {googleSheetsConnected ? 'Connected' : 'Not connected'}
        </span>
        {!googleSheetsConnected && (
          <Link href="/console/google-sheets" className="text-indigo-600 hover:text-indigo-800 hover:underline">
            Connect now
          </Link>
        )}
      </div>

      {autoExportEnabled && (
        <div className="mt-4 space-y-3 border-t border-gray-200 pt-4">
          <div>
            <Label className="text-xs font-semibold uppercase text-gray-600">
              Personal Sheet
            </Label>
            {exportSpreadsheetUrl ? (
              <a
                href={exportSpreadsheetUrl}
                target="_blank"
                rel="noreferrer"
                className="mt-1 block truncate text-sm text-indigo-600 hover:text-indigo-800 hover:underline"
              >
                {exportSpreadsheetUrl}
              </a>
            ) : (
              <p className="mt-1 text-sm text-amber-700">
                No personal sheet linked yet. Set it from{' '}
                <Link href="/console/google-sheets" className="text-indigo-600 hover:text-indigo-800 hover:underline">
                  Google Sheets settings
                </Link>
                .
              </p>
            )}
          </div>

          <div>
            <Label className="text-xs font-semibold uppercase text-gray-600">
              Tab Name (Auto-generated by date)
            </Label>
            <p className="mt-1 rounded-md bg-white px-3 py-2 text-sm font-medium text-gray-700">
              {exportSheetName}
            </p>
            <p className="mt-1 text-xs text-gray-500">
              Data will be exported to a day-wise tab in your personal Google Sheet
            </p>
          </div>

          <div
            className={cn(
              'grid gap-3',
              showInvestmentAmount ? 'grid-cols-1 sm:grid-cols-2' : 'grid-cols-1',
            )}
          >
            {showInvestmentAmount ? (
              <div>
                <Label htmlFor="investment-amount" className="text-xs font-semibold uppercase text-gray-600">
                  Investment Amount (Optional)
                </Label>
                <Input
                  id="investment-amount"
                  type="text"
                  placeholder="e.g., 10000"
                  value={exportInvestmentAmount}
                  onChange={(e) => setExportInvestmentAmount(e.target.value)}
                  className="mt-1 text-sm"
                />
              </div>
            ) : null}
            <div>
              <Label htmlFor="export-title" className="text-xs font-semibold uppercase text-gray-600">
                Title (Optional)
              </Label>
              <Input
                id="export-title"
                type="text"
                placeholder="e.g., Portfolio Analysis"
                value={exportTitle}
                onChange={(e) => setExportTitle(e.target.value)}
                className="mt-1 text-sm"
              />
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}
