import os
import unittest

os.environ.setdefault(
    "DATABASE_URL",
    "postgresql+asyncpg://test:test@localhost:5432/testdb",
)
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")

from app.domains.google_sheets.stock_service import parse_stock_recommendations


class StockServiceParsingTests(unittest.TestCase):
    def test_parse_stock_recommendations_accepts_headerless_canonical_pipe_rows(self):
        response_text = """
## 29 May 2026 | How to Invest INR 50,000 | Generated by GPT-4o

| GPT-4o | NSE | RELIANCE | Reliance Industries Ltd | Breakout from consolidation with high volume | 3150-3170 | 3080 | 3450 | Morgan Stanley, CLSA | 4 | 3160 | 12640 | 9.2 | 8 | 82 | Q4 beat; telecom and retail momentum | Strong uptrend above 50-DMA; volume surge | Accumulation pattern since March | O2C margins stabilizing; retail expansion on track | Jio subscriber additions strong; capex cycle peaking | Bull flag breakout with RSI ~62 | 1 | 29-May-26 | 09:30 IST | GPT-4o |
| GPT-4o | NSE | HDFCBANK | HDFC Bank Ltd | Post-pullback accumulation near support | 1680-1700 | 1640 | 1850 | Nomura, Jefferies | 7 | 1690 | 11830 | 9.5 | 8 | 85 | Strong merger synergies; FII buying resumed | Higher lows forming; MACD bullish crossover | Consolidation breakout above 1700 likely | Margins expanding; NIM stable | Loan growth 15%+; asset quality intact | RSI ~55; ready to break resistance | 2 | 29-May-26 | 09:30 IST | GPT-4o |
| GPT-4o | NSE | INFY | Infosys Ltd | Momentum continuation after earnings beat | 1580-1600 | 1530 | 1720 | Goldman Sachs, UBS | 7 | 1590 | 11130 | 8.8 | 7 | 80 | Large deal wins; AI tailwind | Channel breakout with strong volume | 20-day SMA sloping up | Revenue guidance raised; attrition low | AI-driven demand; cloud pipeline strong | RSI ~60; breakout above 1600 likely | 3 | 29-May-26 | 09:30 IST | GPT-4o |
| GPT-4o | NSE | TCS | Tata Consultancy Services Ltd | Sector rotation into IT; breakout setup | 4100-4130 | 4020 | 4400 | CLSA, Credit Suisse | 3 | 4120 | 12360 | 7.3 | 6 | 78 | Strong deal pipeline; buyback support | Cup and handle formation; volume rising | Relative strength vs Nifty improving | Margins stable; BFSI demand picking up | Gen AI adoption accelerating | RSI ~58; approaching trendline resistance | 4 | 29-May-26 | 09:30 IST | GPT-4o |
| GPT-4o | NSE | MARUTI | Maruti Suzuki India Ltd | Momentum breakout on volume | 12300-12400 | 12000 | 13200 | JPMorgan, BoAML | 0.8 | 12350 | 9880 | 6.9 | 6 | 76 | New model launches; rural demand uptick | 52-week high breakout; accumulation rising | Bullish engulfing pattern weekly | Margins improving; CNG shift positive | Market share recovery; export plans | RSI ~65; momentum indicator bullish | 5 | 29-May-26 | 09:30 IST | GPT-4o |
"""

        stocks = parse_stock_recommendations(response_text)

        self.assertEqual(len(stocks), 5)
        self.assertEqual(stocks[0]["stock_symbol"], "RELIANCE")
        self.assertEqual(stocks[1]["stock_symbol"], "HDFCBANK")
        self.assertEqual(stocks[4]["stock_symbol"], "MARUTI")

    def test_parse_stock_recommendations_accepts_deepseek_coder_canonical_variant(self):
        response_text = """
| DeepSeek R1 | NSE | RELIANCE | Reliance Industries Ltd | Breakout from consolidation with high volume | 2850 - 2900 | 2720 | 3300 | Motilal Oswal | 7 | 2890 | 20230 | 13.0 | 7 | 82 | Strong volume breakout above resistance, bullish on retail and telecom | Sustained outperformance vs Nifty50, institutional accumulation | Robust retail and Jio performance, capex plans | Diversified conglomerate with stable growth drivers | Breakout with above-average volumes, RSI bullish | 1 | 2025-03-27 | 09:30 | DeepSeek R1 |
| DeepSeek R1 | NSE | HDFCBANK | HDFC Bank Ltd | Pullback to support with strong rebound | 1750 - 1780 | 1680 | 1950 | Jefferies | 8 | 1765 | 14120 | 9.8 | 8 | 78 | Reversal from 50-DMA, strong support at 1750 | Steady uptrend, outperforming financials index | Strong loan growth, steady NIM, low NPA expectations | Market leader in banking with solid fundamentals | Bullish engulfing pattern with volume confirmation | 2 | 2025-03-27 | 09:30 | DeepSeek R1 |
| DeepSeek R1 | NSE | ICICIBANK | ICICI Bank Ltd | Momentum continuation with higher highs breakout | 1250 - 1270 | 1190 | 1380 | CLSA | 6 | 1260 | 7560 | 9.5 | 6 | 80 | Price broke above previous high on heavy volume | Outperforming peers, strong trend from last 3 months | Strong earnings momentum, improved asset quality | Consistent performer with digital banking edge | Follow-through day confirming uptrend | 3 | 2025-03-27 | 09:30 | DeepSeek R1 |
| DeepSeek R1 | NSE | BAJFINANCE | Bajaj Finance Ltd | Flag formation breakout with volume | 7200 - 7300 | 6850 | 8000 | Morgan Stanley | 1 | 7250 | 7250 | 10.3 | 8 | 76 | Flag breakout on strong volumes, RSI above 60 | Consolidation breakout, relative strength improving | Strong AUM growth, stable asset quality, digital push | Leader in consumer finance, scalable model | Bullish flag breakout, MACD crossover | 4 | 2025-03-27 | 09:30 | DeepSeek R1 |
| DeepSeek R1 | NSE | TATASTEEL | Tata Steel Ltd | Accumulation after correction, base formation | 150 - 155 | 140 | 175 | Kotak Securities | 40 | 153 | 6120 | 12.9 | 9 | 74 | Base breakout above 155 with increased volume | Accumulation phase, higher lows forming | Steel prices stabilizing, strong domestic demand | Beneficiary of infrastructure push, low valuations | Cup-and-handle pattern formation | 5 | 2025-03-27 | 09:30 | DeepSeek R1 |
"""

        stocks = parse_stock_recommendations(response_text)

        self.assertEqual(len(stocks), 5)
        self.assertEqual(stocks[0]["stock_symbol"], "RELIANCE")
        self.assertEqual(stocks[2]["stock_symbol"], "ICICIBANK")
        self.assertEqual(stocks[4]["stock_symbol"], "TATASTEEL")
        self.assertEqual(stocks[0]["llm"], "DeepSeek R1")


if __name__ == "__main__":
    unittest.main()
