from app.domains.google_sheets.stock_service import (
    format_stocks_for_sheet,
    parse_complete_stock_recommendations,
)


def test_rebalance_markdown_table_parses_and_formats_for_sheets():
    response = """## 31 May 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Demo Model
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NSE | ABC | 10 | Hold | 0 | 10 | Breakout | 100-105 | 95 | 120 | Reuters | 0 | 102 | 0 | 15 | 82 | Strong setup | constructive | improving | stable | catalyst | quality |
"""

    rows = parse_complete_stock_recommendations(response)

    assert len(rows) == 1
    assert rows[0]["action"] == "Hold"
    assert rows[0]["current_units"] == "10"

    headers, sheet_rows = format_stocks_for_sheet(rows)

    assert headers[:6] == [
        "Exchange Symbol",
        "Stock Symbol",
        "Current Units",
        "Action (Buy/Add/Sell All/Trim/Hold/Buy New)",
        "Units Change",
        "Final Units",
    ]
    assert sheet_rows[0][:6] == ["NSE", "ABC", 10, "Hold", 0, 10]
