from app.domains.google_sheets.stock_service import (
    format_stocks_for_sheet,
    parse_complete_stock_recommendations,
)


def test_rebalance_markdown_table_parses_and_formats_for_sheets():
    response = """## 31 May 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Demo Model
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NSE | ABC | 10 | Hold | 0 | 10 | Breakout | 100-105 | 95 | 120 | Reuters | 0 | 102 | 0 | 15 | 82 | Strong setup | constructive | improving | stable | catalyst | quality |
"""

    rows = parse_complete_stock_recommendations(response)

    assert len(rows) == 1
    assert rows[0]["action"] == "Hold"
    assert rows[0]["current_units"] == "10"

    headers, sheet_rows = format_stocks_for_sheet(rows)

    assert headers == [
        "Exchange Symbol",
        "Stock Symbol",
        "Current Units",
        "Action (Buy/Add/Sell All/Trim/Hold/Buy New)",
        "Units Change",
        "Final Units",
        "Technical Setup",
        "Entry Range",
        "Stop Loss",
        "Target",
        "Analyst/Source",
        "Units to Buy",
        "Price Per Unit",
        "Total Buy Amount",
        "Upside Horizon (% return in weeks)",
        "Confidence Score (0-100)",
        "Rationale Remarks",
        "Rationale - Technical setup (short term (1-3 months)",
        "Rationale - Technical setup (medium term)",
        "Rationale - Technical setup (long term term)",
        "Rationale - Fundamentals Short term",
        "Rationale - Fundamentals Medium/Long Term",
    ]
    assert sheet_rows[0][:6] == ["NSE", "ABC", 10, "Hold", 0, 10]


def test_rebalance_table_validation_canonicalizes_complete_rows():
    from app.domains.jobs.tasks import _validate_rebalance_table_content

    response = """## 01 Jun 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Gemini
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NSE | ABC | 10 | Trim | -4 | 6 | Losing momentum | 98-102 | 92 | 112 | Exchange data | 0 | 100 | 0 | 12 | 74 | Trim risk | support weakening | rangebound | long trend intact | no near catalyst | quality intact |
"""

    normalized, issue, rows = _validate_rebalance_table_content(response)

    assert issue is None
    assert len(rows) == 1
    assert rows[0]["stock_symbol"] == "ABC"
    assert "Action (Buy/Add/Sell All/Trim/Hold/Buy New)" in normalized
    assert "| NSE | ABC | 10 | Trim | -4 | 6 |" in normalized


def test_rebalance_table_validation_flags_header_only_output():
    from app.domains.jobs.tasks import _validate_rebalance_table_content

    response = """## 01 Jun 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Gemini
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
"""

    _normalized, issue, rows = _validate_rebalance_table_content(response)

    assert issue == "malformed table output (no data rows)"
    assert rows == []


def test_rebalance_table_validation_flags_missing_current_portfolio_holdings():
    from app.domains.jobs.tasks import _validate_rebalance_table_content

    prompt = """[REBALANCE_FLOW:india]
## 1. Latest Portfolio Snapshot
Snapshot date: 2026-06-01; captured at: 2026-06-01T09:15:00Z

| Exchange | Stock Symbol | Current Units | Average Price | Last Price |
| --- | --- | --- | --- | --- |
| NSE | ABC | 10 | 100 | 102 |
| BSE | XYZ | 5 | 200 | 198 |

## 2. Completed Swing Trade Runs After Previous Market Close
| Exchange Symbol | Stock Symbol | Technical Setup |
| --- | --- | --- |
| NSE | FRESH | Breakout |
"""
    response = """## 01 Jun 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Gemini
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NSE | ABC | 10 | Hold | 0 | 10 | Breakout holding | 100-105 | 95 | 120 | Exchange data | 0 | 102 | 0 | 15 | 82 | Keep winner | constructive | improving | stable | catalyst | quality |
"""

    _normalized, issue, rows = _validate_rebalance_table_content(response, prompt)

    assert issue is not None
    assert "missing 1 current portfolio holding row(s): BSE:XYZ" in issue
    assert len(rows) == 1


def test_rebalance_table_validation_allows_all_current_holdings_plus_buy_new():
    from app.domains.jobs.tasks import _validate_rebalance_table_content

    prompt = """[REBALANCE_FLOW:india]
## 1. Latest Portfolio Snapshot
| Exchange | Stock Symbol | Current Units | Average Price | Last Price |
| --- | --- | --- | --- | --- |
| NSE | ABC | 10 | 100 | 102 |
| BSE | XYZ | 5 | 200 | 198 |

## 2. Completed Swing Trade Runs After Previous Market Close
| Exchange Symbol | Stock Symbol | Technical Setup |
| --- | --- | --- |
| NSE | FRESH | Breakout |
"""
    response = """## 01 Jun 2026 | Recommended Rebalance | Aggressive Swing Portfolio | Generated by Gemini
| Exchange Symbol | Stock Symbol | Current Units | Action (Buy/Add/Sell All/Trim/Hold/Buy New) | Units Change | Final Units | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks | Rationale - Technical setup (short term (1-3 months) | Rationale - Technical setup (medium term) | Rationale - Technical setup (long term term) | Rationale - Fundamentals Short term | Rationale - Fundamentals Medium/Long Term |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| NSE | ABC | 10 | Hold | 0 | 10 | Breakout holding | 100-105 | 95 | 120 | Exchange data | 0 | 102 | 0 | 15 | 82 | Keep winner | constructive | improving | stable | catalyst | quality |
| BSE | XYZ | 5 | Trim | -2 | 3 | Weakening trend | 190-200 | 180 | 220 | Exchange data | 0 | 198 | 0 | 11 | 70 | Trim laggard | support weak | rangebound | stable | limited catalyst | quality mixed |
| NSE | FRESH | 0 | Buy New | 4 | 4 | Strong breakout | 500-510 | 470 | 600 | Exchange data | 4 | 505 | 2020 | 18 | 84 | Stronger setup | breakout | momentum | improving | catalyst | quality |
"""

    normalized, issue, rows = _validate_rebalance_table_content(response, prompt)

    assert issue is None
    assert len(rows) == 3
    assert "| BSE | XYZ | 5 | Trim | -2 | 3 |" in normalized
    assert "| NSE | FRESH | 0 | Buy New | 4 | 4 |" in normalized
