from app.core.logging import get_logger
from app.db.database import SessionLocal

logger = get_logger(__name__)

_DEFAULT_PROMPT_NAME = "India Swing-Trading Research"

_DEFAULT_PROMPT_BODY = """\
Act as a top-tier India aggressive swing-trading strategist combining the skills of a hedge fund trader, technical analyst, momentum screener, and sell-side strategist.

Objective:
Identify the BEST long aggressive swing-trade opportunities in India equities right now for deploying exactly INR 10,000 today, targeting maximum returns over the next 1–3 months.

Use only fresh, recent, and credible market intelligence such as:
- Brokerage upgrades/downgrades
- Institutional research notes
- Earnings reactions
- CNBC/Bloomberg/Reuters interviews
- Verified X/Twitter commentary from respected traders/analysts
- Sector rotation trends
- Relative strength / momentum scans
- Price-volume breakout setups

Selection Rules:
1. Choose exactly 5 stocks.
2. Focus on liquid names only (high average volume, easy execution).
3. Prefer stocks showing:
   - breakout or pre-breakout structures
   - strong momentum with volume confirmation
   - accumulation after pullback
   - bullish catalysts/newsflow
   - sector tailwinds (AI, semis, fintech, biotech, energy, defense, etc.)
4. Avoid weak, illiquid, overextended, purely speculative, or low-conviction names.
5. Mix reward potential with probability of success.

Capital Allocation Rules:
- Total capital = INR 10,000 only
- Use fractional shares if needed
- Optimize for expected return, not diversification for its own sake

Analysis Method:
For each stock, evaluate:
- Trend strength
- Support/resistance
- Risk/reward ratio
- Catalyst strength
- Relative strength vs Index
- Volume behavior
- Probability of reaching target in 2–12 weeks

Output Rules:
Return ONLY one markdown table.
No intro. No explanation. No notes. No disclaimer. No text before or after the table.

Title:
## [TODAY'S DATE] | How to Invest INR 10,000 | Generated by [LLM Name + Model]

Table Columns:
| Stock Name | Technical Setup | Entry Range | Stop Loss | Target | Analyst/Source | Units to Buy | Price Per Unit | Total Buy Amount | Upside Horizon (% return in weeks) | Confidence Score (0-100) | Rationale Remarks |

Formatting Rules:
- Use realistic current price zones
- Use concise professional wording
- Confidence score must reflect conviction + setup quality
- Upside horizon format example: 12% in 6–8 weeks
- Units to Buy must mathematically fit INR 10,000 total
- Total Buy Amount must sum close to INR 10,000
- Rank rows from highest conviction to lowest
- Use actionable numbers, not vague ranges\
"""


def init_db():
    """
    Initialize database.

    In production, run migrations with:
    $ alembic upgrade head

    Migrations are managed by Alembic. See alembic/versions/
    """
    logger.info("Database initialization - migrations handled by Alembic")
    logger.info("To apply pending migrations, run: alembic upgrade head")
    _seed_default_prompt()


def _seed_default_prompt() -> None:
    from app.models.prompt import Prompt

    db = SessionLocal()
    try:
        if db.query(Prompt).first() is not None:
            return
        db.add(Prompt(name=_DEFAULT_PROMPT_NAME, body=_DEFAULT_PROMPT_BODY))
        db.commit()
        logger.info("Seeded default prompt: '%s'", _DEFAULT_PROMPT_NAME)
    except Exception:
        db.rollback()
        logger.exception("Failed to seed default prompt")
    finally:
        db.close()
