"""add_runs_and_run_jobs_tables

Revision ID: ae32a2772ead
Revises: d4e5f6a7b8c9
Create Date: 2026-05-18 15:36:15.146619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.domains.jobs.models import JobStatusType


# revision identifiers, used by Alembic.
revision: str = 'ae32a2772ead'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prompt_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', JobStatusType(length=50), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('synthesis_response', sa.Text(), nullable=True),
    sa.Column('decision_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('run_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_jobs_id'), 'run_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_run_jobs_job_id'), 'run_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_run_jobs_run_id'), 'run_jobs', ['run_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_run_jobs_run_id'), table_name='run_jobs')
    op.drop_index(op.f('ix_run_jobs_job_id'), table_name='run_jobs')
    op.drop_index(op.f('ix_run_jobs_id'), table_name='run_jobs')
    op.drop_table('run_jobs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
