"""add zerodha credentials table

Revision ID: b7560f83a1b2
Revises: ae32a2772ead
Create Date: 2026-05-18 17:43:01.380208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7560f83a1b2'
down_revision: Union[str, Sequence[str], None] = 'ae32a2772ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zerodha_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zerodha_credentials_user_id'), 'zerodha_credentials', ['user_id'], unique=True)
    op.drop_index(op.f('ix_outbox_unpublished'), table_name='outbox', postgresql_where='(published_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outbox_unpublished'), 'outbox', ['created_at'], unique=False, postgresql_where='(published_at IS NULL)')
    op.drop_index(op.f('ix_zerodha_credentials_user_id'), table_name='zerodha_credentials')
    op.drop_table('zerodha_credentials')
    # ### end Alembic commands ###
