"""add zerodha last_used_at

Revision ID: e2b8e9557671
Revises: b7560f83a1b2
Create Date: 2026-05-18 17:56:03.263689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2b8e9557671'
down_revision: Union[str, Sequence[str], None] = 'b7560f83a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zerodha_credentials', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zerodha_credentials', 'last_used_at')
    # ### end Alembic commands ###
