"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, Check, GripVertical, X } from "lucide-react";

import { createBullpenQuestionRow, type BullpenQuestionLlmBreakdownItem, type BullpenQuestionRow } from "@/lib/bullpen-ai";
import { buildBullpenMarketUrl } from "@/lib/bullpenMarketLinks";
import { formatApiTimestamp } from "@/lib/datetime";
import type { BullpenAutoLiveEventTrend, BullpenAutoLiveLlmOutput } from "@/types/api";
import { BullpenReturnsPerDayHeaderInfo } from "./BullpenReturnsPerDayInfo";

type ColumnKey = "event" | "deadline" | "score" | "currentOdds" | "llmOdds" | "returns" | "scans";
type SortDirection = "asc" | "desc";
type Preferences = { order: ColumnKey[]; widths: Record<ColumnKey, number>; sort: { key: ColumnKey; direction: SortDirection } };

const STORAGE_KEY = "bullpen-event-trends-table-v1";
const columns: Array<{ key: ColumnKey; label: string; width: number }> = [
  { key: "event", label: "Event", width: 330 }, { key: "deadline", label: "Deadline", width: 105 },
  { key: "score", label: "Score", width: 90 }, { key: "currentOdds", label: "Current Odds", width: 125 },
  { key: "llmOdds", label: "LLM Odds", width: 125 }, { key: "returns", label: "Returns/day", width: 110 },
  { key: "scans", label: "20 scans · newest to oldest", width: 420 },
];
const defaults: Preferences = { order: columns.map(({ key }) => key), widths: Object.fromEntries(columns.map(({ key, width }) => [key, width])) as Record<ColumnKey, number>, sort: { key: "score", direction: "desc" } };
const odds = (value?: number | null) => value == null ? "—" : `${value.toLocaleString("en-IN", { maximumFractionDigits: 2 })}%`;
const formatTime = (value?: string | null) => formatApiTimestamp(value, { emptyValue: "—", timeZone: "Asia/Kolkata", timeZoneName: "short", second: "2-digit" });
const formatDeadline = (value?: string | null) => value ? formatApiTimestamp(value, { emptyValue: "—", timeZone: "Asia/Kolkata", timeZoneName: "short", year: undefined }) : "—";
const scanColor = (score: number | null) => { if (score === null) return "rgb(203 213 225)"; const n = Math.max(0, Math.min(100, score)); const [a,b,p] = n <= 65 ? [[244,166,160],[255,255,255],(n-50)/15] : [[255,255,255],[82,183,126],(n-65)/35]; const progress = Math.max(0, Math.min(1,p)); return `rgb(${a.map((v,i) => Math.round(v + (b[i]-v)*progress)).join(" ")})`; };

function PolymarketIcon({ className = "" }: { className?: string }) {
  return <svg aria-hidden="true" className={className} viewBox="0 0 64 64" fill="none"><path d="M14 14L50 6V58L14 50V14Z" stroke="currentColor" strokeWidth="5" strokeLinejoin="round"/><path d="M16 16L50 32L16 48" stroke="currentColor" strokeWidth="5" strokeLinejoin="round"/></svg>;
}

function llmItem(output: BullpenAutoLiveLlmOutput): BullpenQuestionLlmBreakdownItem {
  return { provider: output.provider, model: output.model, status: output.status, providerError: output.error, jobId: null, runId: null, timestamp: output.completed_at ?? null, llmYesOdds: output.llm_yes_odds ?? null, llmNoOdds: output.llm_no_odds ?? null, yesDefinition: null, deadlineEt: null, hoursRemaining: null, evidenceStatus: output.evidence_status ?? null, eventState: output.event_state ?? null, confidence: output.confidence ?? null, keyEvidence: output.key_evidence ?? [], redFlags: output.red_flags ?? [], preflightCommentary: output.preflight_commentary ?? null, internetSearchCommentary: output.internet_search_commentary ?? null, finalConclusion: output.final_conclusion ?? null, rationale: output.rationale ?? null, direction: output.direction === "YES_CAMP" || output.direction === "NO_CAMP" || output.direction === "UNCERTAIN" ? output.direction : null, rationaleOddsMismatch: output.rationale_odds_mismatch ?? false, rationaleOddsMismatchReason: output.rationale_odds_mismatch_reason ?? null, effectiveWeight: output.effective_weight ?? null, webSearchUsed: null, webSearchQueries: [], webSources: [], internetVerified: null, evidenceBlockUsed: false, staleFactDetected: false, invalidReason: output.invalid_reason ?? null, invalidStaleFact: false, staleFactReason: null };
}

function currentDaysUntilClose(closeTime: string | null | undefined) {
  if (!closeTime) return null;
  const closeDate = new Date(closeTime);
  if (Number.isNaN(closeDate.getTime())) return null;
  return Math.round(((closeDate.getTime() - Date.now()) / 86_400_000) * 10) / 10;
}

function questionFor(event: BullpenAutoLiveEventTrend, scanIndex = 0): BullpenQuestionRow {
  const outputs = event.scan_llm_outputs?.[scanIndex] ?? [];
  return createBullpenQuestionRow({ id: event.market_id, question: event.market_title, marketId: event.market_id, questionId: event.market_id, closeTime: event.close_time ?? null, category: "", yesOdds: event.current_yes_odds ?? null, noOdds: event.current_no_odds ?? null, volume: null, liquidity: null, sourceUrl: event.market_url ?? "", slug: null, marketUrl: event.market_url ?? null, outcomeLabels: ["Yes", "No"], outcomeCount: 2, isBinaryYesNo: true, daysUntilClose: currentDaysUntilClose(event.close_time), rules: null, marketContext: null, resolutionSource: null, llmYesOdds: scanIndex === 0 ? event.llm_yes_odds ?? null : null, llmNoOdds: scanIndex === 0 ? event.llm_no_odds ?? null : null, returnsPerDay: event.returns_per_day ?? null, llmCompletedAt: event.scan_timestamps[scanIndex] ?? null, llmBreakdown: outputs.map(llmItem) });
}

export const hasStrongestLatestLlmOdds = (event: BullpenAutoLiveEventTrend) => (event.scan_scores[0] ?? -1) >= 80;
export const hasUnavailableReturnsForCurrentPosition = (event: BullpenAutoLiveEventTrend) => event.returns_per_day == null && Boolean(event.is_active_position || event.is_claimable_position);
export const isExpiredNotYetClaimablePosition = (event: BullpenAutoLiveEventTrend) => {
  if (event.is_claimable_position || !event.close_time) return false;
  const closeTime = new Date(event.close_time).getTime();
  return Number.isFinite(closeTime) && closeTime < Date.now();
};

export function BullpenEventTrendsTable({ events, showStrongestOnly = false, onScore, onLlm, onReturns, onReturnsFormula }: { events: BullpenAutoLiveEventTrend[]; showStrongestOnly?: boolean; onScore: (event: BullpenAutoLiveEventTrend) => void; onLlm: (question: BullpenQuestionRow) => void; onReturns: (question: BullpenQuestionRow) => void; onReturnsFormula: () => void }) {
  const [preferences, setPreferences] = useState(defaults);
  const preferencesLoaded = useRef(false);
  const [dragged, setDragged] = useState<ColumnKey | null>(null);
  const [hovered, setHovered] = useState<{ event: BullpenAutoLiveEventTrend; index: number } | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null") as Partial<Preferences> | null; if (saved?.order?.length === columns.length) setPreferences({ order: saved.order, widths: { ...defaults.widths, ...saved.widths }, sort: saved.sort ?? defaults.sort }); } catch { /* Ignore invalid browser preferences. */ } preferencesLoaded.current = true; }); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (preferencesLoaded.current) localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences)); }, [preferences]);
  const sorted = useMemo(() => events.filter(event => !showStrongestOnly || hasStrongestLatestLlmOdds(event) || event.is_active_position || event.is_claimable_position).sort((a,b) => { const aExpiredNotYetClaimable = isExpiredNotYetClaimablePosition(a); const bExpiredNotYetClaimable = isExpiredNotYetClaimablePosition(b); if (aExpiredNotYetClaimable !== bExpiredNotYetClaimable) return aExpiredNotYetClaimable ? -1 : 1; const aClaimable = Boolean(a.is_claimable_position); const bClaimable = Boolean(b.is_claimable_position); if (aClaimable !== bClaimable) return aClaimable ? -1 : 1; const aReturnsUnavailable = hasUnavailableReturnsForCurrentPosition(a); const bReturnsUnavailable = hasUnavailableReturnsForCurrentPosition(b); if (aReturnsUnavailable !== bReturnsUnavailable) return aReturnsUnavailable ? -1 : 1; const key = preferences.sort.key; const value = (event: BullpenAutoLiveEventTrend): string | number => key === "event" ? event.market_title.toLocaleLowerCase() : key === "deadline" ? (event.close_time ? new Date(event.close_time).getTime() : Number.MAX_SAFE_INTEGER) : key === "score" ? event.score : key === "currentOdds" ? event.current_yes_odds ?? -1 : key === "llmOdds" ? event.llm_yes_odds ?? -1 : key === "returns" ? event.returns_per_day ?? -1 : event.scan_scores.filter(v => v != null).length; const left=value(a), right=value(b); return (left < right ? -1 : left > right ? 1 : a.market_title.localeCompare(b.market_title)) * (preferences.sort.direction === "asc" ? 1 : -1); }), [events, preferences.sort, showStrongestOnly]);
  const template = preferences.order.map(key => `${preferences.widths[key]}px`).join(" ");
  const sort = (key: ColumnKey) => setPreferences(p => ({ ...p, sort: { key, direction: p.sort.key === key && p.sort.direction === "asc" ? "desc" : "asc" } }));
  const resize = (key: ColumnKey, event: ReactPointerEvent) => { event.preventDefault(); const startX=event.clientX, start=preferences.widths[key]; const move=(e: PointerEvent) => setPreferences(p => ({ ...p, widths: { ...p.widths, [key]: Math.max(72, start + e.clientX-startX) } })); const up=()=>{ window.removeEventListener("pointermove",move); window.removeEventListener("pointerup",up); }; window.addEventListener("pointermove",move); window.addEventListener("pointerup",up); };
  const cell = (key: ColumnKey, event: BullpenAutoLiveEventTrend) => {
    const activePositionSide = event.is_active_position ? event.active_position_side?.trim().toUpperCase() : null;
    const activeSideClass = "rounded bg-green-600 px-1 text-white ring-1 ring-green-200/80 shadow-sm shadow-green-950/30 dark:bg-green-400 dark:text-slate-950 dark:ring-green-100";
    if (key === "event") return <span className="flex min-w-0 items-center gap-2">{event.is_active_position && <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-green-600 text-white ring-2 ring-green-200/80 shadow-sm shadow-green-950/40 dark:bg-green-400 dark:text-slate-950 dark:ring-green-100" title={`Active Bullpen position: ${event.active_position_side ?? "unknown side"}`}><Check className="h-4 w-4 stroke-[4.5]" aria-label="Active Bullpen position" /></span>}<a className="truncate text-xs font-semibold hover:text-sky-700 hover:underline" title={`Open ${event.market_title} in Bullpen`} href={buildBullpenMarketUrl(event.market_id)} target="_blank" rel="noreferrer">{event.market_title}</a>{event.market_url && <a className="shrink-0 text-blue-600 hover:text-blue-800" title={`Open ${event.market_title} on Polymarket`} aria-label={`Open ${event.market_title} on Polymarket`} href={event.market_url} target="_blank" rel="noreferrer"><PolymarketIcon className="h-4 w-4" /></a>}</span>;
    if (key === "deadline") return event.is_claimable_position ? <span className="inline-flex min-w-20 items-center justify-center rounded-lg bg-green-700 px-3 py-1.5 text-sm font-black uppercase tracking-wide text-white shadow-md ring-2 ring-green-300 dark:bg-green-500 dark:text-slate-950 dark:ring-green-200" title="This resolved winning position is available to claim now">Claim</span> : <span className="text-xs font-semibold" title={formatTime(event.close_time)}>{formatDeadline(event.close_time)}</span>;
    if (key === "score") return <button className="text-right text-xs font-bold underline decoration-dotted" onClick={() => onScore(event)}>{event.score.toFixed(2)}</button>;
    if (key === "currentOdds") return <span className="text-xs font-semibold">Yes {odds(event.current_yes_odds)}<br/>No {odds(event.current_no_odds)}</span>;
    if (key === "llmOdds") return event.llm_yes_odds == null && event.llm_no_odds == null ? (event.scan_llm_outputs?.[0]?.length ? <button className="text-left text-xs font-semibold text-slate-500 underline decoration-dotted" title="No valid LLM odds were produced. Open the saved model output and failure reason." onClick={() => onLlm(questionFor(event))}>Not covered<br/>in latest scan</button> : <span className="text-xs font-semibold text-slate-500" title="This event was not covered by an LLM in the latest scan.">Not covered<br/>in latest scan</span>) : <button className="text-left text-xs font-semibold text-violet-700 underline" onClick={() => onLlm(questionFor(event))}><span className={activePositionSide === "YES" ? activeSideClass : undefined} title={activePositionSide === "YES" ? "Active Bullpen position: YES" : undefined}>Yes {odds(event.llm_yes_odds)}</span><br/><span className={activePositionSide === "NO" ? activeSideClass : undefined} title={activePositionSide === "NO" ? "Active Bullpen position: NO" : undefined}>No {odds(event.llm_no_odds)}</span></button>;
    if (key === "returns") return <button className="text-left text-xs font-bold underline decoration-dotted" disabled={event.returns_per_day == null} onClick={() => onReturns(questionFor(event))}>{odds(event.returns_per_day)}</button>;
    return <span className="flex gap-1.5">{event.scan_scores.map((score,i) => <button key={i} type="button" disabled={score == null} onMouseEnter={() => score != null && setHovered({event,index:i})} onMouseLeave={() => setHovered(null)} onFocus={() => score != null && setHovered({event,index:i})} onBlur={() => setHovered(null)} onClick={() => score != null && onLlm(questionFor(event,i))} aria-label={score == null ? `Scan ${i+1}: not covered` : `Open scan ${i+1} LLM details`} className={`flex h-5 w-5 items-center justify-center rounded-full border shadow-sm ${score != null && score >= 80 ? "border-[1.5px] border-black ring-1 ring-black/30 dark:border-white dark:ring-white/60" : "border-slate-700/60 ring-1 ring-slate-900/10 dark:border-slate-100/80 dark:ring-white/30"}`} style={{backgroundColor:scanColor(score)}}>{score != null && event.scan_sides?.[i] === "YES" ? <Check className="h-3.5 w-3.5 rounded-full bg-white/85 p-px stroke-[4.5] text-blue-800 shadow-sm"/> : score != null && event.scan_sides?.[i] === "NO" ? <X className="h-3.5 w-3.5 rounded-full bg-white/85 p-px stroke-[4.5] text-red-800 shadow-sm"/> : null}</button>)}</span>;
  };
  return <div className="relative overflow-x-auto px-4 py-2"><div style={{minWidth: preferences.order.reduce((sum,key)=>sum+preferences.widths[key],0)}}>
    <div className="grid gap-3 border-b px-1 pb-2" style={{gridTemplateColumns:template}}>{preferences.order.map(key => { const item=columns.find(c=>c.key===key)!; const active=preferences.sort.key===key; return <div key={key} draggable onDragStart={() => setDragged(key)} onDragOver={e=>e.preventDefault()} onDrop={()=>{ if(dragged && dragged!==key) setPreferences(p=>{const order=p.order.filter(k=>k!==dragged); order.splice(order.indexOf(key),0,dragged); return {...p,order};}); setDragged(null); }} className="relative flex items-center text-[10px] font-bold uppercase text-slate-500"><GripVertical className="mr-1 h-3 w-3 cursor-grab"/><button className="flex items-center gap-1" onClick={()=>sort(key)}>{item.label}{active ? preferences.sort.direction === "asc" ? <ArrowUp className="h-3 w-3"/> : <ArrowDown className="h-3 w-3"/> : <ArrowUpDown className="h-3 w-3 opacity-40"/>}</button>{key === "returns" && <BullpenReturnsPerDayHeaderInfo onOpen={onReturnsFormula} className="ml-1 h-4 w-4" />}<button aria-label={`Resize ${item.label} column`} className="absolute -right-1 h-full w-2 cursor-col-resize border-r border-transparent hover:border-slate-400" onPointerDown={e=>resize(key,e)}/></div>})}</div>
    {sorted.map((event,rowIndex)=>{ const expiredNotYetClaimable = isExpiredNotYetClaimablePosition(event); const claimable = Boolean(event.is_claimable_position); const returnsUnavailable = hasUnavailableReturnsForCurrentPosition(event); const activeBelowThreshold = showStrongestOnly && event.is_active_position && !hasStrongestLatestLlmOdds(event); return <div key={event.market_id} data-expired-not-yet-claimable={expiredNotYetClaimable || undefined} data-claimable={claimable || undefined} data-returns-unavailable={returnsUnavailable || undefined} data-active-below-llm-threshold={activeBelowThreshold || undefined} className={`grid items-center gap-3 border-b px-1 py-1.5 ${expiredNotYetClaimable ? "bg-emerald-100 text-emerald-950 ring-1 ring-inset ring-emerald-400 dark:bg-emerald-400/20 dark:text-emerald-50 dark:ring-emerald-500" : claimable ? "bg-emerald-300 text-emerald-950 ring-2 ring-inset ring-emerald-600 dark:bg-emerald-700 dark:text-white dark:ring-emerald-400" : returnsUnavailable ? "bg-emerald-100 text-emerald-950 ring-1 ring-inset ring-emerald-400 dark:bg-emerald-400/20 dark:text-emerald-50 dark:ring-emerald-500" : activeBelowThreshold ? "bg-red-100 text-red-950 ring-1 ring-inset ring-red-400" : rowIndex===9 ? "border-b-4 border-b-red-500" : "border-slate-200/70"}`} style={{gridTemplateColumns:template}}>{preferences.order.map(key=><div key={key} className="min-w-0">{cell(key,event)}</div>)}</div>;})}
  </div>{hovered && <div role="tooltip" className="pointer-events-none fixed bottom-5 right-5 z-[190] max-h-[55vh] w-[32rem] overflow-auto rounded-2xl border border-slate-300 bg-slate-950 p-4 text-white shadow-2xl"><p className="text-xs font-semibold">{formatTime(hovered.event.scan_timestamps[hovered.index])} · Strongest LLM side: {hovered.event.scan_sides[hovered.index] ?? "—"} · {odds(hovered.event.scan_scores[hovered.index])}</p><div className="mt-3 space-y-3">{(hovered.event.scan_llm_outputs?.[hovered.index] ?? []).map((output,index)=><div key={`${output.provider}-${output.model}-${index}`} className="border-t border-slate-700 pt-2"><p className="text-xs font-bold">{output.provider} · {output.model}</p><p className="text-xs text-emerald-300">Yes {odds(output.llm_yes_odds)} · No {odds(output.llm_no_odds)}{output.effective_weight != null ? ` · Weight ${output.effective_weight}` : ""}</p><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-slate-200">{output.final_conclusion || output.rationale || output.internet_search_commentary || output.preflight_commentary || output.invalid_reason || output.error || "No commentary saved."}</p></div>)}{!(hovered.event.scan_llm_outputs?.[hovered.index]?.length) && <p className="text-xs text-slate-300">This legacy scan retained its consensus score but not the individual model payload.</p>}</div><p className="mt-3 text-[10px] text-slate-400">Click the event circle to keep these details open.</p></div>}</div>;
}
