import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import ts from "typescript";

function read(relativePath) {
  return readFileSync(new URL(relativePath, import.meta.url), "utf8");
}

function transpileTypeScript(relativePath, moduleKind = ts.ModuleKind.ESNext) {
  const source = read(relativePath);
  const result = ts.transpileModule(source, {
    compilerOptions: {
      module: moduleKind,
      target: ts.ScriptTarget.ES2022,
      jsx: ts.JsxEmit.ReactJSX,
    },
    fileName: relativePath,
    reportDiagnostics: true,
  });
  const errors = (result.diagnostics ?? []).filter(
    (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error,
  );
  assert.deepEqual(
    errors.map((diagnostic) =>
      ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n"),
    ),
    [],
  );
  return result.outputText;
}

function loadUrlsModule() {
  const output = transpileTypeScript("../lib/urls.ts", ts.ModuleKind.CommonJS);
  const loaded = { exports: {} };
  const evaluate = new Function(
    "exports",
    "module",
    "require",
    "process",
    output,
  );
  evaluate(
    loaded.exports,
    loaded,
    (specifier) => {
      if (specifier === "@/services/session") {
        return { sessionStorage: { getUserData: () => null } };
      }
      throw new Error(`Unexpected runtime import: ${specifier}`);
    },
    {
      env: {
        NODE_ENV: "production",
        NEXT_PUBLIC_API_URL: "https://api.cred-x.in",
      },
    },
  );
  return loaded.exports;
}

test("authenticated browser API reads stay on the same-origin BFF", () => {
  const originalWindow = globalThis.window;
  globalThis.window = {
    location: {
      hostname: "cred-x.in",
      origin: "https://cred-x.in",
      protocol: "https:",
    },
  };

  try {
    const { URLs, resolveApiReadTransportCandidates } = loadUrlsModule();
    const runUrl = `${URLs.runs.list()}?page=1&limit=100`;
    const candidates = resolveApiReadTransportCandidates(runUrl);
    assert.deepEqual(candidates, [
      {
        url: "/backend-api/runs?page=1&limit=100",
        stage: "primary",
        transport: "same-origin-proxy",
      },
    ]);
  } finally {
    globalThis.window = originalWindow;
  }
});

test("same-origin backend health checks remain public", () => {
  const source = read("../app/backend-api/[...path]/route.ts");

  assert.match(source, /const PUBLIC_BACKEND_PATHS = new Set\(\[/);
  assert.match(source, /"health\/live"/);
  assert.match(source, /"health\/ready"/);
  assert.match(source, /PUBLIC_BACKEND_PATHS\.has\(path\)/);
});

test("dashboard threat latest reads skip historical augmentation unless explicitly requested", () => {
  const routerSources = [
    read("../../backend/app/domains/zerodha/threats_router.py"),
    read("../../backend/app/domains/indmoney_us/threats_router.py"),
  ];

  for (const source of routerSources) {
    assert.match(
      source,
      /include_history: bool = Query\(\s*default=False,/,
    );
    assert.match(source, /include_history=include_history/);
    assert.match(
      source,
      /if include_history:\s*parsed = await _augment_report_with_urgent_history/,
    );
  }
});
test("large full-run list requests are capped while summary lists remain unaffected", () => {
  const source = read("../../backend/app/domains/runs/repository.py");

  assert.match(source, /MAX_FULL_RUN_LIST_LIMIT = 20/);
  assert.match(
    source,
    /if not summary and query\.limit > MAX_FULL_RUN_LIST_LIMIT/,
  );
  assert.match(
    source,
    /PagedQuery\(\s*page=query\.page,\s*limit=MAX_FULL_RUN_LIST_LIMIT,/,
  );
  assert.match(source, /offset\(effective_query\.offset\)/);
  assert.match(source, /limit\(effective_query\.limit\)/);
});

test("the production frontend exposes an immutable build fingerprint", () => {
  const source = read("../app/api/runtime-fingerprint/route.ts");
  const deployWorkflow = read("../../.github/workflows/deploy.yml");
  const stampScript = read("../../scripts/stamp-frontend-build.mjs");

  assert.match(source, /GENERATED_BUILD_SHA/);
  assert.match(source, /GENERATED_BUILD_TIMESTAMP/);
  assert.match(source, /@\/lib\/generatedBuildInfo/);
  assert.match(source, /Cache-Control/);
  assert.match(source, /no-store/);
  assert.match(deployWorkflow, /scripts\/stamp-frontend-build\.mjs/);
  assert.match(stampScript, /Generated by the production deployment workflow\./);
  assert.match(stampScript, /\.join\("\\n"\)/);
  assert.doesNotMatch(stampScript, /\.join\("\\\\n"\)/);
});

test("Auto-Live start ambiguity uses two read-only reconciliations and never repeats the POST", () => {
  const source = read("../services/api.ts");
  const method = source.match(
    /runBullpenAutoLiveOnce\([\s\S]*?\n  startBullpenAutoLive\(\)/,
  )?.[0];

  assert.ok(method);
  assert.equal(
    method.match(/this\.post<BullpenAutoLiveRun>/g)?.length,
    1,
  );
  assert.match(method, /client_run_id: clientRunId/);
  assert.match(method, /this\.getBullpenAutoLiveRun\(clientRunId/);
  assert.match(method, /this\.getBullpenAutoLiveRuns\(/);
  assert.match(method, /isBullpenAutoLiveRunResponse/);
  assert.match(method, /logBullpenRunStartFallback/);
  assert.match(source, /bullpen_auto_live_run_start_fallback_triggered/);
  assert.doesNotMatch(method, /while\s*\(/);
});

test("dashboard tertiary fallbacks validate age-bounded saved data", () => {
  const dashboardSource = read(
    "../app/console/dashboard/DashboardPageClient.tsx",
  );
  const actionablesSource = read(
    "../app/console/_components/FinalActionablesConsole.tsx",
  );

  assert.match(dashboardSource, /isValidDashboardCacheValue/);
  assert.match(dashboardSource, /dashboard_read_fallback_triggered/);
  assert.match(dashboardSource, /last-known-good-cache/);
  assert.match(dashboardSource, /dashboard_refresh_deduplicated/);
  assert.match(actionablesSource, /DASHBOARD_FINAL_ACTIONABLES_CACHE_MAX_AGE_MS/);
  assert.match(actionablesSource, /final_actionables_fallback_triggered/);
  assert.match(actionablesSource, /final_actionables_refresh_deduplicated/);
});

test("changed fallback TypeScript modules parse", () => {
  for (const relativePath of [
    "../lib/urls.ts",
    "../services/api.ts",
    "../app/backend-api/[...path]/route.ts",
    "../app/api/runtime-fingerprint/route.ts",
    "../lib/generatedBuildInfo.ts",
    "../app/console/bullpen-ai/_components/bullpenAutoRunStatus.ts",
    "../app/console/dashboard/DashboardPageClient.tsx",
    "../app/console/_components/FinalActionablesConsole.tsx",
  ]) {
    transpileTypeScript(relativePath);
  }
});
